# cert-manager-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 20h0m0s
  chart:
    spec:
      chart: cert-manager
      version: v1.17.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: cert-manager
  values:
    global:
      priorityClassName: system-cluster-critical
    fullnameOverride: cert-manager
    crds:
      enabled: true
    dns01RecursiveNameservers: "1.1.1.1:53"