apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kibana
      version: 7.17.3
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: logging
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"

    replicas: 1

    image: "docker.elastic.co/kibana/kibana"
    imageTag: "7.17.3"
    imagePullPolicy: "IfNotPresent"

    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

    protocol: http

    serverHost: "0.0.0.0"

    healthCheckPath: "/app/kibana"

    service:
      type: ClusterIP
      port: 5601

    ingress:
      enabled: true
      className: "nginx"
      pathtype: ImplementationSpecific
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: kibana.uat.devkuban.com
          paths:
            - path: /

    lifecycle:
      postStart:
        exec:
          command:
            - bash
            - -c
            - |
              #!/bin/bash
              # Wait for Elasticsearch to be ready
              while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' http://elasticsearch-master:9200)" != "200" ]]; do
                echo "Waiting for Elasticsearch..."
                sleep 5
              done
              echo "Elasticsearch is ready!"

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
