apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      version: 20.0.5
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: nginx
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: monitoring-prometheus
        jobLabel: app.kubernetes.io/name
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: nginx.uat.devkuban.com
      path: /
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-http01-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      ingressClassName: "nginx"
      tls: true
      extraTls:
        - hosts:
            - nginx.uat.devkuban.com
          secretName: nginx-uat-tls
      