apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      version: 20.0.5
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  targetNamespace: nginx
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hostname: nginx.uat.devkuban.com
      path: /
      annotations:
          kubernetes.io/ingress.class: nginx
      ingressClassName: "nginx"
      