apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 8h0m0s
  install:
    createNamespace: true
  targetNamespace: monitoring
  values:
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - alertmanager.uat.devkuban.com
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - prometheus.uat.devkuban.com

    grafana:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - grafana.uat.devkuban.com
        
   