apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: default
  chart:
    spec:
      chart: nginx
      version: "20.0.1"
      sourceRef:
        kind: OCIRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    replicaCount: 2