apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: kyverno-repo
        namespace: flux-system
  interval: 1h
  timeout: 30m
  install:
    createNamespace: true
  targetNamespace: kyverno
  values:
    config:
      create: true